<a href="https://colab.research.google.com/github/Shraddha6211/Machine-Learning-Extra-Class/blob/main/ANN_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import files
files.upload()


Saving car_purchasing.csv to car_purchasing.csv


{'car_purchasing.csv': b'customer name,JobTitle,customer e-mail,country,gender,age,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,credit card debt,net worth,car purchase amount\r\nMartina Avila,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,42,167411.18,0,400184.25,,567595.43,567595.43,11609.38091,238961.2505,35321.45877\r\nHarlan Barnes,CAPTAIN III (POLICE DEPARTMENT),eu.dolor@diam.co.uk,Belize,0,41,155966.02,245131.88,137811.38,,538909.28,538909.28,9572.957136,530973.9078,45115.52566\r\nNaomi Rodriquez,CAPTAIN III (POLICE DEPARTMENT),vulputate.mauris.sagittis@ametconsectetueradipiscing.co.uk,Algeria,1,43,212739.13,106088.18,16452.6,,335279.91,335279.91,11160.35506,638467.1773,42925.70921\r\nJade Cunningham,WIRE ROPE CABLE MAINTENANCE MECHANIC,malesuada@dignissim.com,Cook Islands,1,58,77916,56120.71,198306.9,,332343.61,332343.61,14426.16485,548599.0524,67422.36313\r\nCedric Leach,"DEPUTY CHIEF OF DEPARTMENT,

In [7]:
import pandas as pd

df= pd.read_csv('car_purchasing.csv', encoding='latin1')
df.head(3)

,customer name,JobTitle,customer e-mail,country,gender,age,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,credit card debt,net worth,car purchase amount
0,Martina Avila,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,42,167411.18,0.00,400184.25,NaN,567595.43,567595.43,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,CAPTAIN III (POLICE DEPARTMENT),eu.dolor@diam.co.uk,Belize,0,41,155966.02,245131.88,137811.38,NaN,538909.28,538909.28,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,CAPTAIN III (POLICE DEPARTMENT),vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43,212739.13,106088.18,16452.60,NaN,335279.91,335279.91,11160.355060,638467.1773,42925.70921


In [8]:
df= df.drop([
    'customer name',
    'customer e-mail',
    'country',
    'Benefits',
    'JobTitle'

], axis =1)
df.sample(3)

,gender,age,BasePay,OvertimePay,OtherPay,TotalPay,TotalPayBenefits,credit card debt,net worth,car purchase amount
69,1,52,115455.44,104632.95,14776.81,234865.20,234865.20,13685.887020,356553.3996,49392.88970
230,1,51,202426.74,0.00,0.00,202426.74,202426.74,5011.615145,563498.6636,52654.40455
232,1,46,139580.96,33418.92,29333.37,202333.25,202333.25,16127.566190,494985.5363,46054.60253


In [9]:
X = df.drop('car purchase amount', axis =1)
y = df['car purchase amount']
X.head(3)

,gender,age,BasePay,OvertimePay,OtherPay,TotalPay,TotalPayBenefits,credit card debt,net worth
0,0,42,167411.18,0.00,400184.25,567595.43,567595.43,11609.380910,238961.2505
1,0,41,155966.02,245131.88,137811.38,538909.28,538909.28,9572.957136,530973.9078
2,1,43,212739.13,106088.18,16452.60,335279.91,335279.91,11160.355060,638467.1773


In [12]:
# Create 3 classes using quantiles
y_class =pd.qcut(
    y,
    q=3,
    labels=[0,1,2]
)

# Convert category to int
y_class = y_class.astype(int)

In [13]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report, confusion_matrix



In [14]:
y_cat = to_categorical(y_class, num_classes=3)
y_cat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.2, random_state=42)

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(3, activation='softmax')       # 3 categorical outputs
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [19]:
history = model.fit(
    X_train,
    y_train,
    epochs = 10,
    batch_size = 32,
    validation_split = 0.2,
    verbose =1
)

Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.3594 - loss: 1.1057 - val_accuracy: 0.3875 - val_loss: 1.0603
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5219 - loss: 0.9970 - val_accuracy: 0.5125 - val_loss: 1.0172
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6031 - loss: 0.9221 - val_accuracy: 0.5750 - val_loss: 0.9627
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6531 - loss: 0.8524 - val_accuracy: 0.5750 - val_loss: 0.9123
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6812 - loss: 0.7952 - val_accuracy: 0.5875 - val_loss: 0.8780
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6812 - loss: 0.7552 - val_accuracy: 0.5375 - val_loss: 0.8641
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6844 - loss: 0.7241 - val_accuracy: 0.5750 - val_loss: 0.8530
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6844 - loss: 0.7055 - val_accuracy: 0.5750 - v

In [21]:
y_pred = np.argmax(model.predict(X_test), axis=-1)
y_true = np.argmax(y_test, axis=-1)

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[23  5  0]
 [ 7 15 13]
 [ 2  6 29]]
              precision    recall  f1-score   support

           0       0.72      0.82      0.77        28
           1       0.58      0.43      0.49        35
           2       0.69      0.78      0.73        37

    accuracy                           0.67       100
   macro avg       0.66      0.68      0.66       100
weighted avg       0.66      0.67      0.66       100

